[package]
name = "apotheosis2"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-only"

[dependencies]
rand_pcg = "0.3.1"
rand_core = "0.6.3"
rand = { version = "0.8", features = ["std_rng"] }
libm = "0.2.1"
tlsh2 = { git = "https://github.com/danielhuici/tlsh", features = ["diff", "serde"] }
serde_json = "1.0.145"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
gexf = { git = "https://github.com/danielhuici/gexf" }
serde = { version ="1.0.228", features = ["derive"] }
bincode = "1.3.3"
axum = "0.8.8"


[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
